// VKey - Localized String Dictionary
// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include <cstdint>

namespace NextKey {

/// UI display language
enum class Language : uint8_t { Vietnamese = 0, English = 1 };

/// String table identifiers
enum class StringId : uint16_t {
    // Tray menu
    MENU_TOGGLE_VIET,
    MENU_SPELL_CHECK,
    MENU_SMART_SWITCH,
    MENU_MACRO_TOGGLE,
    MENU_MACRO_CONFIG,
    MENU_CONVERT_TOOL,
    MENU_QUICK_CONVERT,
    MENU_INPUT_METHOD,
    MENU_CODE_TABLE,
    MENU_UNICODE_COMPOUND,
    MENU_SETTINGS,
    MENU_ABOUT,
    MENU_EXIT,
    MENU_STOP_WATCHDOG,
    MENU_ENABLE_WATCHDOG,
    MENU_EXTENSIONS,
    MENU_EXT_BROWSER,
    MENU_EXT_WATCHDOG,

    // Tooltips
    TIP_VIETNAMESE,
    TIP_ENGLISH,

    // About dialog
    ABOUT_TITLE,
    ABOUT_BODY,

    // Update
    UPDATE_TITLE,
    UPDATE_AVAILABLE_TITLE,
    UPDATE_AVAILABLE_BODY,
    UPDATE_NOW,
    UPDATE_SKIP,
    UPDATE_LATEST,
    UPDATE_FAILED,
    UPDATE_DOWNLOADING,
    UPDATE_CHANGELOG,
    UPDATE_SUCCESS,
    UPDATE_INSTALL_FAILED,
    UPDATE_CHECK_NOW,
    UPDATE_CHECKING,
    UPDATE_DOWNLOAD_FAILED,

    // Update-restart banner (hybrid TSF DLL update)
    UPDATE_BANNER_PENDING,
    UPDATE_BANNER_MISMATCH,
    UPDATE_BANNER_RESTART_NOW,
    UPDATE_BANNER_LATER,
    UPDATE_BANNER_CONFIRM,       // final reboot confirmation prompt

    // Convert tool
    CONVERT_NO_SOURCE_FILE,
    CONVERT_READ_ERROR,
    CONVERT_CLIPBOARD_EMPTY,
    CONVERT_NO_DEST_FILE,
    CONVERT_WRITE_ERROR,
    CONVERT_CLIPBOARD_WRITE_ERROR,
    CONVERT_SUCCESS,

    // TSF registration
    TSF_REGISTER_SUCCESS,
    TSF_UNREGISTER_SUCCESS,
    TSF_UNREGISTER_FAILED,

    // Excluded apps
    EXCLUDED_CANNOT_SELF,

    // Import/Export shared prompts
    IMPORT_KEEP_EXISTING,
    IMPORT_FILE_OPEN_FAILED,
    EXPORT_FILE_WRITE_FAILED,

    // Admin restart
    ADMIN_DEELEVATION_FAILED,

    // Watchdog
    WATCHDOG_STOPPED_BODY,
    WATCHDOG_ENABLED_BODY,
    BROWSER_EXT_STOPPED_BODY,
    BROWSER_EXT_ENABLED_BODY,
    UPDATE_BACKUP_SUCCESS,
    SPELL_ADVANCED_REQUIRED_TITLE,
    SPELL_ADVANCED_DOWNLOAD_PROMPT,
    SPELL_ADVANCED_DOWNLOAD_AUTO,
    SPELL_ADVANCED_INSTALL_MANUAL,
    SPELL_ADVANCED_USE_STANDARD,
    SPELL_ADVANCED_NOT_ENABLED_TITLE,
    SPELL_ADVANCED_MANUAL_TITLE,
    SPELL_ADVANCED_MANUAL_BODY,
    SPELL_ADVANCED_MANUAL_FINISH,
    SPELL_ADVANCED_MANUAL_LINK,
    SPELL_ADVANCED_OPEN_FOLDER,
    SPELL_ADVANCED_OPEN_TARGET_FAILED,
    SPELL_ADVANCED_FALLBACK_CHOICE,
    SPELL_ADVANCED_FAILURE_FALLBACK_CHOICE,
    SPELL_ADVANCED_DOWNLOADING,
    SPELL_ADVANCED_NETWORK_FAILED,
    SPELL_ADVANCED_VERIFY_FAILED,
    SPELL_ADVANCED_INSTALL_FAILED,
    SPELL_ADVANCED_CLOSE_APP,
    SPELL_ADVANCED_LOAD_APP,
    MACRO_CONFIRM_DELETE,
    MACRO_CONFIRM_DELETE_MULTI,

    _COUNT
};

/// Set the active UI language (thread-safe)
void SetLanguage(Language lang) noexcept;

/// Get the active UI language (thread-safe)
[[nodiscard]] Language GetLanguage() noexcept;

/// Look up a localized string by ID (zero-overhead array lookup)
[[nodiscard]] const wchar_t* S(StringId id) noexcept;

}  // namespace NextKey
